a:
  datasource:
    url: jdbc:mysql://host-application:3306/a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gsmrlab
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.lj.a.model

logging:
  level:
    com:
      lj:
        pri:
          dao: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#dubbo配置
dubbo:
  application:
    name: a-provider # 服务名
  scan:
    base-packages: com.lj.a.service.impl
  registry:
    address: zookeeper://host-application:2181 # 注册中心地址
  protocol:
    name: dubbo # 指定通信协议
    id: dubbo
    port: 20884 # 通信端口  这里指的是与消费者间的通信协议与端口
  consumer:
    loadbalance: roundrobin
    check: false

server:
  port: 8084
