#mysql配置
pri:
  datasource:
    url: jdbc:mysql://host-application:3306/pri0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gsmrlab
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  type-aliases-package: com.lj.pri.model
#mybatis日志配置
logging:
  level:
    com:
      lj:
        pri:
          dao: debug
#mybatis翻页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#dubbo配置
dubbo:
  metadata-report:
    address: zookeeper://host-application:2181
  application:
    name: pri-provider # 服务名
    qos-port: 33333
  scan:
    base-packages: com.lj.pri.service.impl
  registry:
    address: zookeeper://host-application:2181 # 注册中心地址
  protocol:
    name: dubbo # 指定通信协议
    id: dubbo
    port: 20882 # 通信端口  这里指的是与消费者间的通信协议与端口
  consumer:
    loadbalance: roundrobin
    check: false
  config-center:
    address: zookeeper://host-application:2181

server:
  port: 8082

spring:
  cloud:
    sentinel:
      transport:
        dashboard: host-application:9090
      #取消Sentinel控制台懒加载
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true